/**
 * Flat-file publications -- the `file` part.
 *
 * Easy to forget entirely, because JSON is the common case and the flat-file
 * path only breaks in production. These are real, openable files (a PDF viewer
 * will render the PDF), built by hand so there is no dependency to keep
 * patched.
 */
import { caseName, judicialName, PROVENANCE, TEST_SENTINEL, type Jurisdiction } from './people.js';
import type { Rng } from './random.js';
import { caseNumber, channel, courtRoomName, hearingType, type Venue } from './vocab.js';

export interface FlatFile {
  bytes: Uint8Array;
  /** CaTH names flat files `{uuid}.{ext}`. */
  name: string;
  mime: string;
}

const encoder = new TextEncoder();

function escapePdfText(text: string): string {
  return text.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)');
}

/**
 * A minimal but genuinely valid PDF 1.4: catalogue, pages, one page, a Helvetica
 * font and a content stream, with a correct xref table.
 */
export function buildPdf(lines: string[]): Uint8Array {
  const content = [
    'BT',
    '/F1 14 Tf',
    '50 780 Td',
    '18 TL',
    ...lines.map((line) => `(${escapePdfText(line.slice(0, 95))}) Tj T*`),
    'ET',
  ].join('\n');

  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>',
    `<< /Length ${content.length} >>\nstream\n${content}\nendstream`,
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
  ];

  let pdf = '%PDF-1.4\n';
  const offsets: number[] = [];
  objects.forEach((body, index) => {
    offsets.push(pdf.length);
    pdf += `${index + 1} 0 obj\n${body}\nendobj\n`;
  });

  const xrefStart = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (const offset of offsets) pdf += `${String(offset).padStart(10, '0')} 00000 n \n`;
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF\n`;

  return encoder.encode(pdf);
}

function csvCell(value: string): string {
  return /[",\n]/.test(value) ? `"${value.replace(/"/g, '""')}"` : value;
}

export function buildCsv(header: string[], rows: string[][]): Uint8Array {
  const lines = [header, ...rows].map((row) => row.map(csvCell).join(','));
  return encoder.encode(`${lines.join('\r\n')}\r\n`);
}

export interface FlatFileOptions {
  rng: Rng;
  listType: string;
  jurisdiction: Jurisdiction;
  venue: Venue;
  contentDate: Date;
  publicationId: string;
  format?: 'pdf' | 'csv' | 'html';
  rows?: number;
}

export function generateFlatFile(options: FlatFileOptions): FlatFile {
  const { rng, listType, jurisdiction, venue, contentDate, publicationId } = options;
  const format = options.format ?? rng.weighted([
    ['pdf', 70],
    ['csv', 20],
    ['html', 10],
  ] as const);
  const rowCount = options.rows ?? rng.int(6, 24);

  const rows = Array.from({ length: rowCount }, () => {
    const hour = rng.weighted([[10, 45], [11, 10], [12, 5], [14, 30], [15, 10]]);
    const minute = rng.pick([0, 15, 30, 45]);
    return {
      time: `${String(hour).padStart(2, '0')}:${String(minute).padStart(2, '0')}`,
      room: courtRoomName(rng),
      number: caseNumber(rng, jurisdiction),
      name: caseName(rng, jurisdiction),
      type: hearingType(rng, jurisdiction),
      channel: channel(rng),
      judge: judicialName(rng),
    };
  }).sort((a, b) => a.time.localeCompare(b.time));

  const heading = `${venue.name} -- ${listType.replace(/_/g, ' ')}`;
  const dateLine = `Content date: ${contentDate.toISOString().slice(0, 10)}   Provenance: ${PROVENANCE}`;

  if (format === 'csv') {
    return {
      bytes: buildCsv(
        ['Time', 'Court room', 'Case number', 'Case name', 'Hearing type', 'Channel', 'Judiciary'],
        rows.map((r) => [r.time, r.room, r.number, r.name, r.type, r.channel, r.judge]),
      ),
      name: `${publicationId}.csv`,
      mime: 'text/csv',
    };
  }

  if (format === 'html') {
    const html = [
      '<!DOCTYPE html>',
      '<html lang="en"><head><meta charset="utf-8">',
      `<title>${heading}</title></head><body>`,
      `<h1>${heading}</h1>`,
      `<p>${dateLine}</p>`,
      '<table><thead><tr><th>Time</th><th>Court room</th><th>Case number</th>',
      '<th>Case name</th><th>Hearing type</th><th>Judiciary</th></tr></thead><tbody>',
      ...rows.map(
        (r) =>
          `<tr><td>${r.time}</td><td>${r.room}</td><td>${r.number}</td>` +
          `<td>${r.name}</td><td>${r.type}</td><td>${r.judge}</td></tr>`,
      ),
      '</tbody></table>',
      `<p>${TEST_SENTINEL} Generated by cath-simulator. Not a real court list.</p>`,
      '</body></html>',
    ].join('\n');
    return { bytes: encoder.encode(html), name: `${publicationId}.html`, mime: 'text/html' };
  }

  return {
    bytes: buildPdf([
      heading,
      dateLine,
      `${TEST_SENTINEL} Generated by cath-simulator. Not a real court list.`,
      '',
      ...rows.map((r) => `${r.time}  ${r.room}  ${r.number}  ${r.name}  ${r.type}`),
    ]),
    name: `${publicationId}.pdf`,
    mime: 'application/pdf',
  };
}
