/**
 * Generated by scripts/build-schema-index.mjs -- do not edit by hand.
 *
 * 42 schemas vendored from hmcts/pip-data-management,
 * 99 of 102 list types mapped to one.
 */
/* eslint-disable */

import civilAndFamilyDailyCauseList from '../../../vendor/schemas/civil_and_family_daily_cause_list.json';
import civilDailyCauseList from '../../../vendor/schemas/civil_daily_cause_list.json';
import copDailyCauseList from '../../../vendor/schemas/cop_daily_cause_list.json';
import crownDailyPddaList from '../../../vendor/schemas/crown_daily_pdda_list.json';
import crownFirmPddaList from '../../../vendor/schemas/crown_firm_pdda_list.json';
import crownWarnedPddaList from '../../../vendor/schemas/crown_warned_pdda_list.json';
import etDailyList from '../../../vendor/schemas/et_daily_list.json';
import etFortnightlyPressList from '../../../vendor/schemas/et_fortnightly_press_list.json';
import familyDailyCauseList from '../../../vendor/schemas/family_daily_cause_list.json';
import iacDailyList from '../../../vendor/schemas/iac_daily_list.json';
import magistratesAdultCourtList from '../../../vendor/schemas/magistrates_adult_court_list.json';
import magistratesPublicAdultCourtList from '../../../vendor/schemas/magistrates_public_adult_court_list.json';
import magistratesPublicList from '../../../vendor/schemas/magistrates_public_list.json';
import magistratesStandardList from '../../../vendor/schemas/magistrates_standard_list.json';
import masterSchema from '../../../vendor/schemas/master_schema.json';
import nonStrategicAstDailyHearingList from '../../../vendor/schemas/non-strategic__ast_daily_hearing_list.json';
import nonStrategicCicWeeklyHearingList from '../../../vendor/schemas/non-strategic__cic_weekly_hearing_list.json';
import nonStrategicCommonKbChdDailyCauseList from '../../../vendor/schemas/non-strategic__common_kb_chd_daily_cause_list.json';
import nonStrategicCommonNsDailyCauseList from '../../../vendor/schemas/non-strategic__common_ns_daily_cause_list.json';
import nonStrategicCourtOfAppealCivilDailyCauseList from '../../../vendor/schemas/non-strategic__court_of_appeal_civil_daily_cause_list.json';
import nonStrategicCstWeeklyHearingList from '../../../vendor/schemas/non-strategic__cst_weekly_hearing_list.json';
import nonStrategicFttLandRegistryTribunalWeeklyHearingList from '../../../vendor/schemas/non-strategic__ftt-land-registry-tribunal-weekly-hearing-list.json';
import nonStrategicFttResidentialPropertyTribunalWeeklyHearingList from '../../../vendor/schemas/non-strategic__ftt-residential-property-tribunal-weekly-hearing-list.json';
import nonStrategicFttTaxChamberTribunalWeeklyHearingList from '../../../vendor/schemas/non-strategic__ftt-tax-chamber-tribunal-weekly-hearing-list.json';
import nonStrategicGrcWeeklyHearingList from '../../../vendor/schemas/non-strategic__grc_weekly_hearing_list.json';
import nonStrategicInterimApplicationsChanceryDivisionDailyCauseList from '../../../vendor/schemas/non-strategic__interim_applications_chancery_division_daily_cause_list.json';
import nonStrategicLondonAdministrativeCourtDailyCauseList from '../../../vendor/schemas/non-strategic__london_administrative_court_daily_cause_list.json';
import nonStrategicPhtWeeklyHearingList from '../../../vendor/schemas/non-strategic__pht_weekly_hearing_list.json';
import nonStrategicSendDailyHearingList from '../../../vendor/schemas/non-strategic__send_daily_hearing_list.json';
import nonStrategicSeniorCourtsCostsOfficeDailyCauseList from '../../../vendor/schemas/non-strategic__senior_courts_costs_office_daily_cause_list.json';
import nonStrategicSiacWeeklyHearingList from '../../../vendor/schemas/non-strategic__siac_weekly_hearing_list.json';
import nonStrategicSscsDailyHearingList from '../../../vendor/schemas/non-strategic__sscs_daily_hearing_list.json';
import nonStrategicUtAdministrativeAppealsChamberDailyHearingList from '../../../vendor/schemas/non-strategic__ut_administrative_appeals_chamber_daily_hearing_list.json';
import nonStrategicUtIacJudicialReviewsDailyHearingList from '../../../vendor/schemas/non-strategic__ut_iac_judicial_reviews_daily_hearing_list.json';
import nonStrategicUtIacJudicialReviewsLondonDailyHearingList from '../../../vendor/schemas/non-strategic__ut_iac_judicial_reviews_london_daily_hearing_list.json';
import nonStrategicUtIacStatutoryAppealsDailyHearingList from '../../../vendor/schemas/non-strategic__ut_iac_statutory_appeals_daily_hearing_list.json';
import nonStrategicUtLandsChamberDailyHearingList from '../../../vendor/schemas/non-strategic__ut_lands_chamber_daily_hearing_list.json';
import nonStrategicUtTaxAndChanceryChamberDailyHearingList from '../../../vendor/schemas/non-strategic__ut_tax_and_chancery_chamber_daily_hearing_list.json';
import nonStrategicWpafccWeeklyHearingList from '../../../vendor/schemas/non-strategic__wpafcc_weekly_hearing_list.json';
import singleJusticeProcedurePress from '../../../vendor/schemas/single_justice_procedure_press.json';
import singleJusticeProcedurePublic from '../../../vendor/schemas/single_justice_procedure_public.json';
import sscsDailyList from '../../../vendor/schemas/sscs_daily_list.json';

export type JsonSchema = Record<string, unknown>;

export const SCHEMAS: Record<string, JsonSchema> = {
  "civil_and_family_daily_cause_list.json": civilAndFamilyDailyCauseList as JsonSchema,
  "civil_daily_cause_list.json": civilDailyCauseList as JsonSchema,
  "cop_daily_cause_list.json": copDailyCauseList as JsonSchema,
  "crown_daily_pdda_list.json": crownDailyPddaList as JsonSchema,
  "crown_firm_pdda_list.json": crownFirmPddaList as JsonSchema,
  "crown_warned_pdda_list.json": crownWarnedPddaList as JsonSchema,
  "et_daily_list.json": etDailyList as JsonSchema,
  "et_fortnightly_press_list.json": etFortnightlyPressList as JsonSchema,
  "family_daily_cause_list.json": familyDailyCauseList as JsonSchema,
  "iac_daily_list.json": iacDailyList as JsonSchema,
  "magistrates_adult_court_list.json": magistratesAdultCourtList as JsonSchema,
  "magistrates_public_adult_court_list.json": magistratesPublicAdultCourtList as JsonSchema,
  "magistrates_public_list.json": magistratesPublicList as JsonSchema,
  "magistrates_standard_list.json": magistratesStandardList as JsonSchema,
  "master_schema.json": masterSchema as JsonSchema,
  "non-strategic__ast_daily_hearing_list.json": nonStrategicAstDailyHearingList as JsonSchema,
  "non-strategic__cic_weekly_hearing_list.json": nonStrategicCicWeeklyHearingList as JsonSchema,
  "non-strategic__common_kb_chd_daily_cause_list.json": nonStrategicCommonKbChdDailyCauseList as JsonSchema,
  "non-strategic__common_ns_daily_cause_list.json": nonStrategicCommonNsDailyCauseList as JsonSchema,
  "non-strategic__court_of_appeal_civil_daily_cause_list.json": nonStrategicCourtOfAppealCivilDailyCauseList as JsonSchema,
  "non-strategic__cst_weekly_hearing_list.json": nonStrategicCstWeeklyHearingList as JsonSchema,
  "non-strategic__ftt-land-registry-tribunal-weekly-hearing-list.json": nonStrategicFttLandRegistryTribunalWeeklyHearingList as JsonSchema,
  "non-strategic__ftt-residential-property-tribunal-weekly-hearing-list.json": nonStrategicFttResidentialPropertyTribunalWeeklyHearingList as JsonSchema,
  "non-strategic__ftt-tax-chamber-tribunal-weekly-hearing-list.json": nonStrategicFttTaxChamberTribunalWeeklyHearingList as JsonSchema,
  "non-strategic__grc_weekly_hearing_list.json": nonStrategicGrcWeeklyHearingList as JsonSchema,
  "non-strategic__interim_applications_chancery_division_daily_cause_list.json": nonStrategicInterimApplicationsChanceryDivisionDailyCauseList as JsonSchema,
  "non-strategic__london_administrative_court_daily_cause_list.json": nonStrategicLondonAdministrativeCourtDailyCauseList as JsonSchema,
  "non-strategic__pht_weekly_hearing_list.json": nonStrategicPhtWeeklyHearingList as JsonSchema,
  "non-strategic__send_daily_hearing_list.json": nonStrategicSendDailyHearingList as JsonSchema,
  "non-strategic__senior_courts_costs_office_daily_cause_list.json": nonStrategicSeniorCourtsCostsOfficeDailyCauseList as JsonSchema,
  "non-strategic__siac_weekly_hearing_list.json": nonStrategicSiacWeeklyHearingList as JsonSchema,
  "non-strategic__sscs_daily_hearing_list.json": nonStrategicSscsDailyHearingList as JsonSchema,
  "non-strategic__ut_administrative_appeals_chamber_daily_hearing_list.json": nonStrategicUtAdministrativeAppealsChamberDailyHearingList as JsonSchema,
  "non-strategic__ut_iac_judicial_reviews_daily_hearing_list.json": nonStrategicUtIacJudicialReviewsDailyHearingList as JsonSchema,
  "non-strategic__ut_iac_judicial_reviews_london_daily_hearing_list.json": nonStrategicUtIacJudicialReviewsLondonDailyHearingList as JsonSchema,
  "non-strategic__ut_iac_statutory_appeals_daily_hearing_list.json": nonStrategicUtIacStatutoryAppealsDailyHearingList as JsonSchema,
  "non-strategic__ut_lands_chamber_daily_hearing_list.json": nonStrategicUtLandsChamberDailyHearingList as JsonSchema,
  "non-strategic__ut_tax_and_chancery_chamber_daily_hearing_list.json": nonStrategicUtTaxAndChanceryChamberDailyHearingList as JsonSchema,
  "non-strategic__wpafcc_weekly_hearing_list.json": nonStrategicWpafccWeeklyHearingList as JsonSchema,
  "single_justice_procedure_press.json": singleJusticeProcedurePress as JsonSchema,
  "single_justice_procedure_public.json": singleJusticeProcedurePublic as JsonSchema,
  "sscs_daily_list.json": sscsDailyList as JsonSchema,
};

/** The vendored schema each list type validates against. */
export const SCHEMA_FOR_LIST_TYPE: Record<string, string> = {
  "SJP_PUBLIC_LIST": "single_justice_procedure_public.json",
  "SJP_DELTA_PUBLIC_LIST": "single_justice_procedure_public.json",
  "SJP_PRESS_LIST": "single_justice_procedure_press.json",
  "SJP_DELTA_PRESS_LIST": "single_justice_procedure_press.json",
  "SJP_PRESS_REGISTER": "single_justice_procedure_press.json",
  "CROWN_DAILY_LIST": "master_schema.json",
  "CROWN_FIRM_LIST": "master_schema.json",
  "CROWN_WARNED_LIST": "master_schema.json",
  "MAGISTRATES_PUBLIC_LIST": "magistrates_public_list.json",
  "MAGISTRATES_STANDARD_LIST": "magistrates_standard_list.json",
  "CIVIL_DAILY_CAUSE_LIST": "civil_daily_cause_list.json",
  "FAMILY_DAILY_CAUSE_LIST": "family_daily_cause_list.json",
  "CIVIL_AND_FAMILY_DAILY_CAUSE_LIST": "civil_and_family_daily_cause_list.json",
  "COP_DAILY_CAUSE_LIST": "cop_daily_cause_list.json",
  "ET_FORTNIGHTLY_PRESS_LIST": "et_fortnightly_press_list.json",
  "ET_DAILY_LIST": "et_daily_list.json",
  "SSCS_DAILY_LIST": "sscs_daily_list.json",
  "SSCS_DAILY_LIST_ADDITIONAL_HEARINGS": "sscs_daily_list.json",
  "IAC_DAILY_LIST": "iac_daily_list.json",
  "IAC_DAILY_LIST_ADDITIONAL_CASES": "iac_daily_list.json",
  "CARE_STANDARDS_LIST": "non-strategic__common_ns_daily_cause_list.json",
  "PRIMARY_HEALTH_LIST": "non-strategic__common_ns_daily_cause_list.json",
  "CIC_DAILY_HEARING_LIST": "non-strategic__cic_weekly_hearing_list.json",
  "CST_WEEKLY_HEARING_LIST": "non-strategic__cst_weekly_hearing_list.json",
  "PHT_WEEKLY_HEARING_LIST": "non-strategic__pht_weekly_hearing_list.json",
  "GRC_WEEKLY_HEARING_LIST": "non-strategic__grc_weekly_hearing_list.json",
  "WPAFCC_WEEKLY_HEARING_LIST": "non-strategic__wpafcc_weekly_hearing_list.json",
  "UT_IAC_JR_LONDON_DAILY_HEARING_LIST": "non-strategic__ut_iac_judicial_reviews_london_daily_hearing_list.json",
  "UT_IAC_JR_LEEDS_DAILY_HEARING_LIST": "non-strategic__ut_iac_judicial_reviews_daily_hearing_list.json",
  "UT_IAC_JR_MANCHESTER_DAILY_HEARING_LIST": "non-strategic__ut_iac_judicial_reviews_daily_hearing_list.json",
  "UT_IAC_JR_BIRMINGHAM_DAILY_HEARING_LIST": "non-strategic__ut_iac_judicial_reviews_daily_hearing_list.json",
  "UT_IAC_JR_CARDIFF_DAILY_HEARING_LIST": "non-strategic__ut_iac_judicial_reviews_daily_hearing_list.json",
  "UT_IAC_STATUTORY_APPEALS_DAILY_HEARING_LIST": "non-strategic__ut_iac_statutory_appeals_daily_hearing_list.json",
  "SIAC_WEEKLY_HEARING_LIST": "non-strategic__siac_weekly_hearing_list.json",
  "POAC_WEEKLY_HEARING_LIST": "non-strategic__common_ns_daily_cause_list.json",
  "PAAC_WEEKLY_HEARING_LIST": "non-strategic__common_ns_daily_cause_list.json",
  "FTT_TAX_WEEKLY_HEARING_LIST": "non-strategic__ftt-tax-chamber-tribunal-weekly-hearing-list.json",
  "FTT_LR_WEEKLY_HEARING_LIST": "non-strategic__ftt-land-registry-tribunal-weekly-hearing-list.json",
  "UT_T_AND_CC_DAILY_HEARING_LIST": "non-strategic__ut_tax_and_chancery_chamber_daily_hearing_list.json",
  "UT_LC_DAILY_HEARING_LIST": "non-strategic__ut_lands_chamber_daily_hearing_list.json",
  "UT_AAC_DAILY_HEARING_LIST": "non-strategic__ut_administrative_appeals_chamber_daily_hearing_list.json",
  "RPT_LONDON_WEEKLY_HEARING_LIST": "non-strategic__ftt-residential-property-tribunal-weekly-hearing-list.json",
  "RPT_EASTERN_WEEKLY_HEARING_LIST": "non-strategic__ftt-residential-property-tribunal-weekly-hearing-list.json",
  "RPT_MIDLANDS_WEEKLY_HEARING_LIST": "non-strategic__ftt-residential-property-tribunal-weekly-hearing-list.json",
  "RPT_NORTHERN_WEEKLY_HEARING_LIST": "non-strategic__ftt-residential-property-tribunal-weekly-hearing-list.json",
  "RPT_SOUTHERN_WEEKLY_HEARING_LIST": "non-strategic__ftt-residential-property-tribunal-weekly-hearing-list.json",
  "FTT_RPT_MARKET_RENTS_WEEKLY_HEARING_LIST": "non-strategic__ftt-residential-property-tribunal-weekly-hearing-list.json",
  "AST_DAILY_HEARING_LIST": "non-strategic__ast_daily_hearing_list.json",
  "SSCS_MIDLANDS_DAILY_HEARING_LIST": "non-strategic__sscs_daily_hearing_list.json",
  "SSCS_SOUTH_EAST_DAILY_HEARING_LIST": "non-strategic__sscs_daily_hearing_list.json",
  "SSCS_WALES_AND_SOUTH_WEST_DAILY_HEARING_LIST": "non-strategic__sscs_daily_hearing_list.json",
  "SSCS_SCOTLAND_DAILY_HEARING_LIST": "non-strategic__sscs_daily_hearing_list.json",
  "SSCS_NORTH_EAST_DAILY_HEARING_LIST": "non-strategic__sscs_daily_hearing_list.json",
  "SSCS_NORTH_WEST_DAILY_HEARING_LIST": "non-strategic__sscs_daily_hearing_list.json",
  "SSCS_LONDON_DAILY_HEARING_LIST": "non-strategic__sscs_daily_hearing_list.json",
  "MENTAL_HEALTH_TRIBUNAL_HEARING_LIST": "non-strategic__common_ns_daily_cause_list.json",
  "LONDON_ADMINISTRATIVE_COURT_DAILY_CAUSE_LIST": "non-strategic__london_administrative_court_daily_cause_list.json",
  "COUNTY_COURT_LONDON_CIVIL_DAILY_CAUSE_LIST": "non-strategic__common_ns_daily_cause_list.json",
  "CIVIL_COURTS_RCJ_DAILY_CAUSE_LIST": "non-strategic__common_ns_daily_cause_list.json",
  "COURT_OF_APPEAL_CRIMINAL_DAILY_CAUSE_LIST": "non-strategic__common_ns_daily_cause_list.json",
  "FAMILY_DIVISION_HIGH_COURT_DAILY_CAUSE_LIST": "non-strategic__common_ns_daily_cause_list.json",
  "KINGS_BENCH_DIVISION_DAILY_CAUSE_LIST": "non-strategic__common_ns_daily_cause_list.json",
  "KINGS_BENCH_MASTERS_DAILY_CAUSE_LIST": "non-strategic__common_ns_daily_cause_list.json",
  "SENIOR_COURTS_COSTS_OFFICE_DAILY_CAUSE_LIST": "non-strategic__senior_courts_costs_office_daily_cause_list.json",
  "MAYOR_AND_CITY_CIVIL_DAILY_CAUSE_LIST": "non-strategic__common_ns_daily_cause_list.json",
  "INTERIM_APPLICATIONS_CHD_DAILY_CAUSE_LIST": "non-strategic__interim_applications_chancery_division_daily_cause_list.json",
  "INTELLECTUAL_PROPERTY_AND_ENTERPRISE_COURT_DAILY_CAUSE_LIST": "non-strategic__common_kb_chd_daily_cause_list.json",
  "INTELLECTUAL_PROPERTY_LIST_CHD_DAILY_CAUSE_LIST": "non-strategic__common_kb_chd_daily_cause_list.json",
  "LONDON_CIRCUIT_COMMERCIAL_COURT_KB_DAILY_CAUSE_LIST": "non-strategic__common_kb_chd_daily_cause_list.json",
  "PATENTS_COURT_CHD_DAILY_CAUSE_LIST": "non-strategic__common_kb_chd_daily_cause_list.json",
  "PENSIONS_LIST_CHD_DAILY_CAUSE_LIST": "non-strategic__common_kb_chd_daily_cause_list.json",
  "PROPERTY_TRUSTS_PROBATE_LIST_CHD_DAILY_CAUSE_LIST": "non-strategic__common_kb_chd_daily_cause_list.json",
  "REVENUE_LIST_CHD_DAILY_CAUSE_LIST": "non-strategic__common_kb_chd_daily_cause_list.json",
  "TECHNOLOGY_AND_CONSTRUCTION_COURT_KB_DAILY_CAUSE_LIST": "non-strategic__common_kb_chd_daily_cause_list.json",
  "ADMIRALTY_COURT_KB_DAILY_CAUSE_LIST": "non-strategic__common_kb_chd_daily_cause_list.json",
  "BUSINESS_LIST_CHD_DAILY_CAUSE_LIST": "non-strategic__common_kb_chd_daily_cause_list.json",
  "CHANCERY_APPEALS_CHD_DAILY_CAUSE_LIST": "non-strategic__common_kb_chd_daily_cause_list.json",
  "COMMERCIAL_COURT_KB_DAILY_CAUSE_LIST": "non-strategic__common_kb_chd_daily_cause_list.json",
  "COMPANIES_WINDING_UP_CHD_DAILY_CAUSE_LIST": "non-strategic__common_kb_chd_daily_cause_list.json",
  "COMPETITION_LIST_CHD_DAILY_CAUSE_LIST": "non-strategic__common_kb_chd_daily_cause_list.json",
  "FINANCIAL_LIST_CHD_KB_DAILY_CAUSE_LIST": "non-strategic__common_kb_chd_daily_cause_list.json",
  "INSOLVENCY_AND_COMPANIES_COURT_CHD_DAILY_CAUSE_LIST": "non-strategic__common_kb_chd_daily_cause_list.json",
  "COURT_OF_APPEAL_CIVIL_DAILY_CAUSE_LIST": "non-strategic__court_of_appeal_civil_daily_cause_list.json",
  "BIRMINGHAM_ADMINISTRATIVE_COURT_DAILY_CAUSE_LIST": "non-strategic__common_ns_daily_cause_list.json",
  "BRISTOL_AND_CARDIFF_ADMINISTRATIVE_COURT_DAILY_CAUSE_LIST": "non-strategic__common_ns_daily_cause_list.json",
  "MANCHESTER_ADMINISTRATIVE_COURT_DAILY_CAUSE_LIST": "non-strategic__common_ns_daily_cause_list.json",
  "LEEDS_ADMINISTRATIVE_COURT_DAILY_CAUSE_LIST": "non-strategic__common_ns_daily_cause_list.json",
  "PCOL_DAILY_CAUSE_LIST": "non-strategic__common_ns_daily_cause_list.json",
  "SEND_DAILY_HEARING_LIST": "non-strategic__send_daily_hearing_list.json",
  "CIC_WEEKLY_HEARING_LIST": "non-strategic__cic_weekly_hearing_list.json",
  "MAGISTRATES_ADULT_COURT_LIST_DAILY": "magistrates_adult_court_list.json",
  "MAGISTRATES_ADULT_COURT_LIST_FUTURE": "magistrates_adult_court_list.json",
  "MAGISTRATES_PUBLIC_ADULT_COURT_LIST_DAILY": "magistrates_public_adult_court_list.json",
  "MAGISTRATES_PUBLIC_ADULT_COURT_LIST_FUTURE": "magistrates_public_adult_court_list.json",
  "CROWN_DAILY_PDDA_LIST": "crown_daily_pdda_list.json",
  "CROWN_FIRM_PDDA_LIST": "crown_firm_pdda_list.json",
  "CROWN_WARNED_PDDA_LIST": "crown_warned_pdda_list.json",
  "HIGH_COURT_CIVIL_DAILY_CAUSE_LIST": "non-strategic__common_ns_daily_cause_list.json",
  "HIGH_COURT_FAMILY_DAILY_CAUSE_LIST": "non-strategic__common_ns_daily_cause_list.json",
  "BUSINESS_AND_PROPERTY_DAILY_CAUSE_LIST": "non-strategic__common_kb_chd_daily_cause_list.json",
  "CIRCUIT_COMMERCIAL_COURT_DAILY_CAUSE_LIST": "non-strategic__common_kb_chd_daily_cause_list.json",
  "TECHNOLOGY_AND_CONSTRUCTION_COURT_DAILY_CAUSE_LIST": "non-strategic__common_kb_chd_daily_cause_list.json",
};

/**
 * List types with no schema of their own in pip-data-management, generated
 * against master_schema.json instead. Mostly the legacy Crown lists that the PDDA
 * variants replaced.
 */
export const LIST_TYPES_WITHOUT_OWN_SCHEMA: string[] = [
  "CROWN_DAILY_LIST",
  "CROWN_FIRM_LIST",
  "CROWN_WARNED_LIST",
];
